pysam bytes/unicode bug workaround
Needed to use pysam.sort and psyam.index
Normal strings are messed up by pysam, saying

 File "pysam/csamtools.pyx", line 105, in pysam.csamtools._samtools_dispatch (pysam/csamtools.c:3460)
  File "pysam/cutils.pyx", line 117, in pysam.cutils.force_cmdline_bytes (pysam/cutils.c:2446)
  File "pysam/cutils.pyx", line 106, in pysam.cutils.force_bytes (pysam/cutils.c:2245)
TypeError: Expected bytes, got unicode

Workaround is to .encode('ascii') the strings